project:
  type: website

website:
  navbar:
    left:
      - href: home.qmd
        text: Home
      - href: exp.qmd
        text: Experience
      - href: blogs.qmd
        text: Projects
      - href: prof.qmd
        text: Professional Profile

  page-footer:
    right: "&copy; 2024, Jane Zou"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

editor: visual

