project:
  type: website

website:
  navbar:
    left:
      - href: home.qmd
        text: Home
      - href: exp.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      - href: awards.qmd
        text: Awards
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

editor: visual

