---
title: "Experience"
format: html
---

## PricewaterhouseCoopers

::: {style="overflow: hidden;"}
::: {style="float: left;"}
*Associate, Platform Development – Specialized Tax Services*
:::

::: {style="float: right;"}
July 2025 - Present
:::
:::

-   Leading cross-team collaboration to design & deploy generative AI models (including GPT-based LLMs) that automate complex regulatory tax data extraction & validation, reducing manual processing time & improving accuracy in compliance workflows.

::: {style="overflow: hidden;"}
::: {style="float: left;"}
*Data Science Intern*
:::

::: {style="float: right;"}
June 2024 - August 2024
:::
:::

-   Engineered a full-stack AI platform using Streamlit & FastAPI, integrated with Azure Form Recognizer, cutting document processing time from 10 hours to 2 minutes & achieving 99% extraction accuracy across 10,000+ financial records.
-   Improved model precision by 20% through demographic profiling & NLP techniques, boosting classification accuracy in automated tax form analysis.


::: {style="overflow: hidden;"}
::: {style="float: left;"}
*Products & Technology Intern*
:::

::: {style="float: right;"}
June 2023 - August 2023
:::
:::

-   Built a Python-based chatbot and interactive dashboards (Tableau, Plotly) for a national nonprofit, increasing engagement by 70% among 1,200 students and improving service quality metrics by 35% through enhanced data-driven decision-making.

## Jules Stein Eye Institute

::: {style="overflow: hidden;"}
::: {style="float: left;"}
*Data Scientist*
:::

::: {style="float: right;"}
May 2023 - June 2024
:::
:::

-   Published 7 papers in Ophthalmology & American Glaucoma Society journals, applying AI models to 3,000+ patient records to improve glaucoma progression forecasting.
-   Built deep learning models in Python & R to predict visual field degradation, increasing early detection accuracy by 28%.
-   Performed survival analysis & multivariate regression to estimate progression rates, uncovering 5 key prognostic factors used to tailor personalized care plans.

```{=html}
<iframe width="100%" height="500" src="https://www.youtube.com/embed/QSe5alK901A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
::: {#fig-RefCardR}
<iframe width="100%" height="600" src="Research Manuscript - Jane Zou.pdf">

</iframe>
:::

## American Express

::: {style="overflow: hidden;"}
::: {style="float: left;"}
*Lead Machine Learning Engineer*
:::

::: {style="float: right;"}
June 2022 - April 2023
:::
:::

-   Directed a team of 3 engineers to develop an ML pipeline processing 10.4M+ financial records, increasing classification accuracy by 30% & enhancing fraud detection precision.
-   Analyzed campaign performance data using Pandas & Scikit-learn, optimizing resource targeting strategies & improving ROI by 80% across multiple campaigns.
-   Deployed ensemble models in Jupyter Notebook to identify high-probability customer segments, increasing lead conversion by 3x.
-   Automated reporting workflows, reducing model iteration cycle time by 50% & enabling faster stakeholder decision-making.

::: {#fig-RefCardR}
<iframe width="100%" height="500" src="AI Studio Final Project - AMEX Arrival Probability.pdf">

</iframe>
:::
