---
title: "Professional Profile"
---

## Awards

::: {style="overflow: hidden;"}
::: {style="float: left;"}
13th Annual Statistical Association UCLA DataFest Finalist
:::

::: {style="float: right;"}
April 2024
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Visa & Society of Women Engineers Scholarship
:::

::: {style="float: right;"}
May 2023
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Third Place Break Through Tech AI \@ UCLA, MIT, Cornell Tech AI Studio
:::

::: {style="float: right;"}
March 2023
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
UCLA Machine Learning Top Contributor
:::

::: {style="float: right;"}
March 2023
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Major League Hacking Housing Insecurity First Place
:::

::: {style="float: right;"}
February 2023
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Major League Hacking Best Mobile App
:::

::: {style="float: right;"}
February 2023
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Orange County Centennial Scholarship
:::

::: {style="float: right;"}
August 2021
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
NCWIT Aspirations in Computing Affiliate Honorable Mention
:::

::: {style="float: right;"}
June 2021
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Azusa Pacific University President's Scholarship
:::

::: {style="float: right;"}
June 2021
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Voice of Democracy Post 10694 Santa Ana First Place
:::

::: {style="float: right;"}
June 2021
:::
:::

## Professional Membership

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Undergraduate Research Scholars Program
:::

::: {style="float: right;"}
October 2023 - June 2024
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Undergraduate Mathematics Council
:::

::: {style="float: right;"}
October 2022 - June 2024
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
American Statistical Association
:::

::: {style="float: right;"}
May 2022 - April 2024
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
DataResolutions
:::

::: {style="float: right;"}
October 2021 - April 2024
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
UCLA College Scholars Program
:::

::: {style="float: right;"}
October 2021 - March 2024
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
National Student Data Corp
:::

::: {style="float: right;"}
June 2023 - August 2023
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
AT&T Technology Academy
:::

::: {style="float: right;"}
June 2023 - July 2023
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Innovate\@UCLA
:::

::: {style="float: right;"}
March 2022 - May 2023
:::
:::

::: {style="overflow: hidden;"}
::: {style="float: left;"}
Society of Women Engineers
:::

::: {style="float: right;"}
October 2021 - May 2023
:::
:::

## Technical Skills

**Programming Languages:** Python, R, Tableau, Power BI, Git, Microsoft Excel, HTML, CSS

**Machine Learning:** Gradient Boosting, Clustering, Collaborative Filtering, Natural Language Processing (NLP), Artificial Intelligence Safety and Ethics, Time Series Analysis, and Feature Engineering

**Business and Domain Knowledge:** Figma, NetSuite, Product Management, Agile and Scrum Methodologies, GIS, Canva
