---
title: "Projects"
format: html
---

# Sustainable Los Angeles Grand Challenge

### 2024 Energy Report Card
<div style="overflow: hidden;">
  <div style="float: left;">*Research Assistant*</div>
  <div style="float: right;">September 2023 - Present</div>
</div>

- Contribute to innovative projects aimed at addressing environmental challenges in the Los Angeles area. 
- Strong analytical skills and passion for making a positive impact on local communities through research and collaboration.

# DataResolutions

### Chelle AI
<div style="overflow: hidden;">
  <div style="float: left;">*Project Lead*</div>
  <div style="float: right;">January 2024 - Present</div>
</div>

- Developed knowledge graphs by extracting and structuring data from NextJS using web scraping techniques in Python. 
- Utilized NetworkX library to construct and analyze the graph representations, enabling the visualization and exploration of relationships among the extracted entities and their attributes.

### OkTY
<div style="overflow: hidden;">
  <div style="float: left;">*Project Lead*</div>
  <div style="float: right;">September 2023 - December 2023</div>
</div>

- Led a team of five in the comprehensive cleansing and analysis of five diverse datasets containing financial and merchant information, spanning a two-year snapshot of spending data, uncovering nuanced trends in user spending habits, including location-based patterns and distinctive merchant preferences.

### SARE Ladies
<div style="overflow: hidden;">
  <div style="float: left;">*Project Consultant*</div>
  <div style="float: right;">April 2023 - June 2023</div>
</div>

- Applied label encoding to survey responses dataset, assigning unique numerical values to each category.
- Developed a random forest feature importance ranking model to identify characteristics impacting the confidence of survey respondents, focusing on ethnicity and whether they identify as real estate investors.

### EpiData
<div style="overflow: hidden;">
  <div style="float: left;">*Project Lead*</div>
  <div style="float: right;">September 2022 - March 2023</div>
</div>

- Led a team of five in the development of a machine learning pipeline for streaming Internet of Things (IoT) data utilizing the EpiData platform.
- Successfully implemented various regression and classification models, resulting in insightful findings from the streaming data collected from a wireless home sensor and time step accelerator.


### HomeDescription
<div style="overflow: hidden;">
  <div style="float: left;">*Project Consultant*</div>
  <div style="float: right;">January 2022 - June 2022</div>
</div>

- Developed a custom three-dimensional scatterplot function in my programming work to effectively visualize trends between two variables of interest and price
- Generated correlograms to illustrate correlation coefficients between the relevant variables
- Conducted web scraping and HTML parsing on Zillow data.

### Savi
<div style="overflow: hidden;">
  <div style="float: left;">*Project Consultant*</div>
  <div style="float: right;">October 2021 - December 2021</div>
</div>

- Developed a heatmap visualization in Python to model correlations between variables of interest and user paid conversion rate, alongside creating histograms to assess the impact of marital status on binary payment status.

# National Student Data Corp

### Pedestrian IoT Analysis
<div style="overflow: hidden;">
  <div style="float: left;">*Project Lead*</div>
  <div style="float: right;">July 2023 - September 2023</div>
</div>

- Spearheaded cross-functional data science teams, providing strategic direction and overseeing end-to-end project execution to ensure the timely delivery of data-driven solutions. 
- Led the conception and execution of pedestrian data analysis, culminating in a successful showcase. 
- Proficient in implementing Agile method- ologies to optimize project workflows, leveraging expertise in machine learning techniques and algorithms to guide the development of predictive models
- Implemented process improvements and best practices, enhancing efficiency and effectiveness in project execution.

# Epicenter for Action Research

### ParkLink
<div style="overflow: hidden;">
  <div style="float: left;">*Project Manager*</div>
  <div style="float: right;">March 2023 - May 2023</div>
</div>

- Led the development of a user-friendly platform for reserving affordable parking spots for the LA Olympics 2028, utilizing UX design expertise. 
- Conducted user research, created wireframes, and performed competitive analysis. 
- Proficient in Figma for designing wireframes, mockups, and prototypes. - Applied user-centered design principles, conducted market research, and translated business objectives into actionable design solutions. 
- Applied design thinking methodologies to drive innovation and problem-solving.

# QWER Hacks

<div style="overflow: hidden;">
  <div style="float: left;">*Project Manager*</div>
  <div style="float: right;">January 2023</div>
</div>

- Designed and prototyped “Homeless Simulator,” a web and mobile app game addressing the experiences of houselessness for queer women of color in LA. 
- Developed storyline and character biographies, utilizing sto- ryboards, graphic design, and game scripts to shape the narrative. 
- Proficient in troubleshooting code bugs in React JS projects in localhost environments. 
- Secured first place in the housing insecurity track, earning the Major League Hacking fellowship interview fast-track certificate. 
- Experienced in producing and designing video game scripts.
- Skilled in written and verbal communication, including interviewing leading experts in public policy and public health researchers.

# American Statistical Association DataFest
<div style="overflow: hidden;">
  <div style="float: left;">*Project Manager, Developer*</div>
  <div style="float: right;">May 2022</div>
</div>

- Created data visualization models to illustrate correlations within drug resistance efficacy player datasets and conducted research on adolescent behavior and video game prevention programs. 
- Proficient in Python for data visualization, cleaning, and analytics using Matplotlib, Seaborn, and Pandas. 
- Experienced in collaborative team environments, including delegation, presentation, and project debriefing. 
- Demonstrated strong public speaking and presentation skills through industry presentations on ML models.

# Innovate@UCLA

### HYREUS
<div style="overflow: hidden;">
  <div style="float: left;">*Project Manager*</div>
  <div style="float: right;">March 2022 - May 2022</div>
</div>
- Directed the development of a user-friendly recruiting platform designed for young adult job seekers. 
- Conducted user research, devised wireframes, and executed competitive analysis. 
- Proficient in Figma for crafting wireframes, mockups, and prototypes. - Applied user-centric design principles, conducted market research, and translated business goals into practical design solutions. 
- Employed design thinking methodologies to foster innovation and problem-solving.


